version: "3.6"

services:
  activator:
    container_name: kgrid-activator
    environment:
        KGRID_CONFIG: "--kgrid.shelf.cdostore.url=filesystem:file://shelf --cors.url=*  --management.info.git.mode=full"
    image: kgrid/activator:1.0.7
    ports:
      - 8081:8080

  library:
    container_name: kgrid-library
    environment:
      KGRID_CONFIG: "--kgrid.shelf.cdostore.url=filesystem:file://shelf --cors.url=*  --management.info.git.mode=full"
    image: kgrid/library:1.1.3
    ports:
      - 8080:8080


