version: "3.6"

services:
  activator:
    container_name: lion-activator
    environment:
        KGRID_CONFIG: "--kgrid.shelf.cdostore.url=filesystem:file://shelf --cors.url=*  --management.info.git.mode=full"
    image: kgrid/activator:1.1.1
    ports:
      - 8181:8080
    volumes:
      - "activator_shelf:/usr/local/miserver/kgrid/shelf"


  library:
    container_name: lion-library
    environment:
      KGRID_CONFIG: "--kgrid.shelf.cdostore.url=filesystem:file://shelf --cors.url=*  --management.info.git.mode=full"
    image: kgrid/library:1.2.1
    ports:
      - 8182:8080
    volumes:
      - "library_shelf:/usr/local/miserver/kgrid/shelf"

volumes:
  activator_shelf:
  library_shelf:

